### ISSUE TITLE
Load "qualification" dependencies

### ISSUE THREAD

**Issue by jonthegeek** [Gilead-BioStats/gsm.qc#9]
https://github.com/Gilead-BioStats/gsm.qc/blob/ae27d508a968d7a300452382523533972e282287/.github/workflows/qualification-report-dispatch.yaml#L28

```
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check, qualification
```

See https://github.com/Gilead-BioStats/gsm.kri/pull/33
